### ISSUE TITLE
Minimum version of Moodle

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#31] opened 2018-09-24 20:18 UTC
A bug has been reported on the plugin page, JazzQuiz not working on Moodle 3.1.
If possible, we should try to make a version which does work on Moodle 3.1, keeping in mind that 3.1 is end of life in 6-8 months, so a lot of time must not be invested.
In the future, we need to test very carefully with both 3.5 (LTS) and 3.6.  There is no reason to support versions older than 3.5, since they are near end of life or worse.

**Comment by sebastsg** [comment] 2018-10-31 05:10
This is a duplicate of #37 isn't it. Or rather, the other way around. Closing.

**Closed by sebastsg** 2018-10-31 05:10 UTC
Labels: bug
